name: app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Define the app's version and build number
version: 1.0.0+1

# Specify the SDK environment version
environment:
  sdk: '>=3.3.1 <4.0.0'

# Dependencies your application requires
dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.0
  http: ^1.2.2
  share_plus: ^6.3.1
  cupertino_icons: ^1.0.6
  win32: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# Flutter-specific configuration
flutter:
  uses-material-design: true

  # Add asset declarations for images, fonts, or other files
  assets:
    - assets/images/  # Include all images in this directory
    - lib/data/db.json # Example JSON asset for user data

  # Uncomment below if you have custom fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700
